paths:
  /api/products:
    get:
      summary: Este servicio obtiene la lista de todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos se obtuvieron correctamente de la BDD
          content:
            aplication/json:
              schema:
                type: Array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión
    post:
      summary: Este servicio crea un producto
      tags:
        - Products
      responses:
        "201":
          description: Se crea el producto en la BDD
          content:
            application/json:
              schema:
                type: Object
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión
  /api/products/{pid}:
    get:
      summary: Este servicio obtiene un producto a través de su ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se manipula en el servicio
          schema:
            $type: String
      responses:
        "200":
          description: Se obtiene el producto específico de la BDD
          content:
            application/json:
              schema:
                type: Object
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión
    put:
      summary: Este servicio actualiza un producto a través de su ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se manipula en el servicio
          schema:
            $type: String
      responses:
        "200":
          description: El producto se actualizó exitósamente
          content:
            application/json:
              schema:
                type: Object
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión
    delete:
      summary: Este servicio elimina un producto a través de si ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se manipula en el servicio
          schema:
            $type: String
      responses:
      "200":
        description: El producto se eliminó exitósamente de la BDD
      "500":
        description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión
  /api/products/mockingproducts:
    get:
      summary: Este servicio obtiene la lista de productos mockeados
      tags:
        - Products
      responses:
      "200":
        description: Se obtiene una lista de productos mockeada
        content:
            application/json:
              schema:
                type: Object
                items:
                  $ref: '#components/schemas/Product'
      "500":
        description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión
components:
  schemas:
    Product:
      type: Objet
      properties:
        _id:
          type: ObjetId
          description: Id autogenerado por MongoDB al crear el recurso
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        code:
          type: String
          description: Código del producto, asignado por el negocio
        price:
          type: Number
          description:  Precio del producto
        status:
          type: Boolean
          description: Disposición del producto en el negocio
        stock:
          type: Number
          description: Numero de ejemplares disponibles del producto en el negocio
        category:
          type: String
          description: Categoría del producto
        thumbnail:
          type: Array
          description: Arreglo de una o más URL a imágenes del producto
        owner:
          type: String
          description: Creador del recurso en la BDD
      example:
        _id: ObjectId("507f191e810c19729de860ea")
        title: Apple Vision Pro
        description: Es una revolucionaria computadora espacial que fusiona el contenido digital con el mundo físico a la perfección y permite aa los usuarios mantenerse presentes y en contacto con otras personas
        code: 489345
        price: 10000000
        status: true
        stock: 3
        category: tech
        thumbnail: [https://www.img.com/apple-vision-pro/png/1, https://www.img.com/apple-vision-pro/png/2]
        owner: 'ADMIN'